### ISSUE TITLE
Use a self signed certificate with public Keycloak instance

### ISSUE THREAD

**Issue by tdiesler** [tdiesler/nessus-actions#18]
This is by no means a straight forward procedure. Here some initial pointers that I found on the way

https://registry.hub.docker.com/r/jboss/keycloak
https://stackoverflow.com/questions/52674979/keycloak-ssl-setup-using-docker-image

**Comment by tdiesler** [comment]
I got a self signed certificate working in the browser. Then I imported that cert into my java system truststore 

```
keytool -import -alias localhost -file tls.crt -keystore $JAVA_HOME/jre/lib/security/cacerts
```

and got ...

```
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <localhost> doesn't match any of the subject alternative names: []
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:507)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:268)
```

**Comment by tdiesler** [comment]
The above can be fixed following [this](https://stackoverflow.com/questions/50928061/certificate-for-localhost-doesnt-match-any-of-the-subject-alternative-names?answertab=votes#tab-top)

```
-ext "SAN:c=DNS:localhost,IP:127.0.0.1"
```
